Feature
xxkrxx/kadaidemo pull request #1
Opened 2024-08-13 12:47 UTC by xxkrxx

確認お願いします。

2024-08-15 13:48 UTC, xxkrxx commented
お疲れ様です。

不要なテーブルを削除しましたので、再度確認をお願いいたします。
テーブルについての説明も簡単に書きました。
ご確認のほど、よろしくお願いいたします。

administrator: 管理者の基本情報を格納するテーブル。
administrator_posts: 管理者と役職（postsテーブル）の関連を保持する中間テーブル。
administrator_roles: 管理者と権限（rolesテーブル）の関連を保持する中間テーブル。
large_categories: 商品の大カテゴリー情報を格納するテーブル。
large_category: 商品検索に使用される大カテゴリーの情報。
manufacturer: メーカー情報を格納するテーブル。
middle_categories: 商品の中カテゴリー情報を格納するテーブル。
middle_category: 商品検索に使用される中カテゴリーの情報。
order: 注文情報を格納するテーブル。
posts: 役職情報を格納するテーブル。
product: 商品の基本情報を格納するテーブル。
products: 商品管理用のテーブル。
roles: 権限情報を格納するテーブル。
small_categories: 商品の小カテゴリー情報を格納するテーブル。
small_category: 商品検索に使用される小カテゴリーの情報。
store_products: 店舗と商品の関連情報を保持する中間テーブル。
stores: 店舗情報を格納するテーブル。
sub_small_categories: 小カテゴリーのサブカテゴリ情報を格納するテーブル。

2024-08-16 04:59 UTC, uchiyama4929 commented
テーブルの整理ありがとうございます。
small_categoryというテーブルが定義書に記載されていないのですがどんなデータを入れればいいんでしょうか？
システム内でCRUDできる注文情報とかは不要ですが、マスタテーブルは最初に構成しないと動作確認ができないのでテーブル定義書を作成いただきたいです。

同じような名前のテーブルが2つづつ用意されているのは一つだと実装ができなかったということですか？

2024-08-16 07:23 UTC, xxkrxx commented
お疲れ様です。

small_category テーブルについてのご質問ですが、このテーブルは商品検索で使用される小カテゴリーの情報を格納するためのものです。

また、同じような名前のテーブルが2つずつ用意されている件についてですが、
これは実装上の問題を解決するためではなく、それぞれ異なる用途に使われることを意図しているためです。

small_categories テーブルは小カテゴリー情報全般を格納し、
small_category テーブルは主に商品検索で使用される情報を格納しました。

テーブル定義書を作成しましたので、それぞれ再度ご確認をお願いいたします。

2024-08-16 08:33 UTC, uchiyama4929 commented
目的別にテーブルを用意するというのはどういうことなんでしょうか？
見た感じ全く同じ情報が存在しているだけのように見えるんですが、全く同じマスタデータを2つのテーブルにいれるということであってますか？

このような実装だとデータを投入したり削除したりする時に2つのテーブルの整合性を取らないといけないので所謂二重管理状態になってしまってメンテナンス上よろしくないと思います。

それともsmall_categoryテーブルとsmall_categoriesテーブルのnameには別の値が入るということですか？

2024-08-16 09:03 UTC, uchiyama4929 commented
productとproductsも2つありますがこれに関してもテーブル定義書の内容と違っていて、priceという用途不明のカラムが追加されていたりテーブル名もこれだけ複数形が検索用になっていたりして見通しも悪いです。

すべて一つのテーブルで事足りる内容だと思うので修正をお願いします。

2024-08-17 01:44 UTC, xxkrxx commented
現在productsを削除し、productテーブル一つにまとめました。
お手数おかけしますが、対応お願い致します。

2024-08-22 02:08 UTC, uchiyama4929 commented
![image](https://github.com/user-attachments/assets/b3ce8e04-6ad7-48b8-9d5a-d3a653f88f62)
![image](https://github.com/user-attachments/assets/72172aa4-f047-4860-91ec-696ca8b415f8)
商品詳細と商品発注のデータが不整合になっているので修正お願いします。

2024-08-22 02:08 UTC, uchiyama4929 commented
idを改ざんしても店舗に紐づいていない商品が発注できないようにしてください。

2024-08-22 03:15 UTC, xxkrxx commented
商品詳細と商品発注のデータ不整合に関する修正内容

createOrder メソッドを修正し、店舗に紐づいている商品だけが発注できるようにしました。具体的には、StoreProduct を取得し、指定された productId と storeId が一致する場合のみ商品を発注できるようにしました。

在庫が不足している場合、または商品が見つからない場合には、IllegalArgumentException をスローして発注を拒否する処理を追加しました。
正しい店舗情報の設定:

発注する際に、order オブジェクトに対して正しい店舗情報を設定するようにしました。

ID改ざんに関する修正内容

IDを改ざんしても店舗に紐づいていない商品が発注できないようにするための修正を行いました。
具体的には、createOrder メソッド内でStoreProductを取得し、正しい storeId に基づいて商品が発注されることを確認する処理を追加しました。

動作確認も行い、問題はありません。
ご確認のほど、よろしくお願いいたします。

2024-08-22 07:59 UTC, uchiyama4929 requested changes
createOrder()というサービスメソッドが増えたようなのですがどこからも実行されていないみたいです。

画面上の商品名のズレとかは解消されていますが他店舗のオーダーを作れることは変わりないようです。

2024-08-22 07:59 UTC, uchiyama4929 commented on demo/src/main/java/com/example/demo/entity/StoreProduct.java
> +    private StoreProduct storeProduct; // StoreProductエンティティとの関連
新しいカラムが追加されたようなのですがこれは何でしょうか？

store_productsのテーブルにstore_product_idというカラムだとidと同じではないですか？

![Uploading image.png…]()

2024-08-22 11:00 UTC, xxkrxx commented
すみません。
間違えて書いて消すの忘れてました。
再度確認お願い致します。

2024-08-23 10:11 UTC, uchiyama4929 commented
`orderService.createOrder()`の内容を修正いただいたようなのですが、Controllerから呼び出しているのは旧来のメソッドに戻っているようです。

やはり他店鋪の発注を出すことができる状態になっているので修正をお願いします。

毎度修正のたびにコメントが大きく更新されたりで修正箇所が増えてレビュー時にコミットの意図が分かりにくいので不要なコミットをなるべく入れないようにしてもらいたいのと、コミットメッセージが「修正」といった感じのが多いのでもう少し具体的に書くようにしていきましょう。

2024-08-23 12:19 UTC, xxkrxx commented
OrderServiceImplのcreateOrderメソッドに
StoreProduct storeProduct = storeProductRepository.findByProductIdAndStoreId(productId, storeId);
を追加して指定されたproductIdとstoreIdが一致するStoreProductを取得し、その在庫を確認します。これにより、他店への発注を防止しました。

Storeエンティティ
 管理者を取得するためのメソッドが存在していなかったので
public Administrator getAdmin() {
    return administrators.isEmpty() ? null : administrators.get(0);
を追加し、最初の管理者を取得するメソッドが追加され、ストアに関連する管理者情報を簡単に取得できるようになりました。

2024-08-26 02:03 UTC, uchiyama4929 commented
お疲れ様です！
発注機能、無事に動いているようで良かったです！


![image](https://github.com/user-attachments/assets/1f1f39c7-8564-4275-9717-a5bc675a3b2a)

カテゴリ検索機能で不整合なカテゴリの検索ができる様になっているので
上位のカテゴリに基づいて一部カテゴリのみを指定できるように修正をお願いします。

> 不要なコミットをなるべく入れないようにしてもらいたい

こちらの意図が伝わっていないようなのですが、

![image](https://github.com/user-attachments/assets/6f7203d1-ecbe-4828-bbb7-fe11b9f4f16c)
![image](https://github.com/user-attachments/assets/65a2a03c-6562-4f9a-be9a-402c0e574d95)

こういった意味のないコミットを増やさないように気をつけてください。
おそらくChatGPTなどの生成AIでソースを生成しているのかと思いますが、このあたりの配慮ができない状態でソースコードを生成しないようにしてください。

現場では変更意図を説明できないようなコミットはレビューで弾かれてしまうと思うので気をつけていきましょう！

2024-08-29 06:14 UTC, xxkrxx commented
単体・結合テストの実施し問題なしを確認しました。
バグ修正は特にありません。
ご確認お願い致します。

2024-08-29 06:16 UTC, xxkrxx commented
単体・結合テストの実施しました。
テスト仕様書の結果が全てOKにし、問題がない事を確認しました。
バグ修正は特にありません。
ご確認お願い致します。

2024-08-29 23:27 UTC, merged